### ISSUE TITLE
Use terser syntax

### ISSUE THREAD

**Issue by kostasx** [in-tech-gration/kiptrak#12]
https://github.com/in-tech-gration/kiptrak/blob/d2e190546dd7413eafb7ae8b492e01ca8d6f5eb5/server/services/csv-service.ts#L40C5-L40C34

I believe `return [].concat(...records);` can be written like this `return [...records];`

**Comment by asterisg** [comment]
Because records is an array of string arrays, I'm doing that in order to make it a one dimensional array.
