### ISSUE TITLE
Handle errors

### ISSUE THREAD

**Issue by kostasx** [in-tech-gration/kiptrak#15]
https://github.com/in-tech-gration/kiptrak/blob/d2e190546dd7413eafb7ae8b492e01ca8d6f5eb5/server/services/csv-service.ts#L82

The parse might throw an exception.

Also, whenever there's an await, always make sure that errors are handled (e.g. using try/catch).

**Comment by asterisg** [comment]
Forgot to add the #19 here which resolved this. Closing the issue.
